---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-output" (include "vuln-agent.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vuln-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.output.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.output.size }}
  {{- if .Values.persistence.output.storageClass }}
  storageClassName: {{ .Values.persistence.output.storageClass }}
  {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-trivy-cache" (include "vuln-agent.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vuln-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.trivyCache.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.trivyCache.size }}
  {{- if .Values.persistence.trivyCache.storageClass }}
  storageClassName: {{ .Values.persistence.trivyCache.storageClass }}
  {{- end }}
